useEmbeddings=false
openAiApiKey="5f922fc571534517acc85c31d6af4bbf"
dataPath="data/summary/logs/Zookeeper.txt"
logsSourceApplication="Zookeeper"
engines=["gpt3", "gpt4"]
outputDir="out"

[model]
temperature=0.3
maxTokens=250
topP=1
frequencyPenalty=0
presencePenalty=0

[embedding]
useEmbeddings=false
model="text-embedding-ada-002"
deploymentUrl="https://openaics598.openai.azure.com"
resourceEndpoint="cs598"
apiKey="5309dd9cfd0e4e9cadd598ee91321fcf"
openAiApiVersion="2023-05-15"
chunkSize=16  # current limit with Azure OpenAI service. This will likely increase in the future.
openAiApiType="azure"

[embedding.redis]
hostName="redislocal"
port="6379"
indexName="log_data"
kDocs=5